### PR TITLE
Update SIGNATURE.txt

### PR DESCRIPTION
**Pull request by Ben-YuqiLu**

### CODE REVIEW

**Review by yechs — COMMENTED** [review]
@SamChou19815 I think you need to manually [approve the workflow to run on forks](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks). Same for #16

**Comment by SamChou19815** [comment]
> @SamChou19815 I think you need to manually [approve the workflow to run on forks](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks). Same for #16

It's caused by how the workflow is defined. The workflow is only triggered on `push` event, which is under the context of this repo. The PRs are from forks, so the event is not triggered.

For the purpose of easier modification, it's probably easier to change the trigger to `push: master, pull_request`, but I prefer to invite them to the org and start the PR from this repo, so I can enforce the 2FA requirement. I already sent invitations to @Ben-YuqiLu and @GeMini-220. However, it's better to revisit the terms before we put down the signatures.

**Comment by yechs** [comment]
> It's caused by how the workflow is defined. The workflow is only triggered on `push` event, which is under the context of this repo. The PRs are from forks, so the event is not triggered.

I see! I didn't know that before. Thanks for clarifying

**Comment by Ben-YuqiLu** [comment]
Closing this PR

**Pull request closed without merging**
